# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13EgMJYGxIYrvAVo43kCI_LxiOKCUkZys

# **Artificial Neural Network for Regression**
"""

import pandas as pd
import tensorflow as tf
import numpy as np
from sklearn.preprocessing import StandardScaler

tf.__version__

"""## **Part 1: Data Preprocessing**

Importing the Dataset
"""

df = pd.read_excel('Folds5x2_pp.xlsx')
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

print(X)

"""Splitting the Dataset"""

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

"""## **Part 2: Building The ANN**

Initialize The ANN
"""

ann = tf.keras.models.Sequential()

"""Adding The Input Layer And The First Hidden Layer"""

ann.add(tf.keras.layers.Dense(units=6, activation='relu', input_shape = (4,)))

#The Dense() class create fully dense connection between the input layers and the first hidden layer

"""Adding The Second Hidden Layer"""

ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

"""Adding The Output Layer"""

ann.add(tf.keras.layers.Dense(units=1))

"""## **Part 3: Training The ANN**

Compiling The ANN
"""

ann.compile(optimizer='adam', loss='mean_squared_error')

"""Training The ANN"""

ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

"""1. Epoch 1 loss was enormous (355,218)
This is because the data was not scaled/normalised. The features (temperature, pressure, etc.) are on very different scales, causing large initial errors.

2. Loss dropped dramatically in early epochs
From 355,218 → ~30 within just 40 epochs — the Adam optimiser is working well.

3. Loss plateaued from ~Epoch 40 onwards
The loss is fluctuating between 24 – 30 and not improving further. This suggests the model has converged at this point.

Predicting The Results of Test Set
"""

y_pred = ann.predict(X_test)
np.set_printoptions(precision=2)
np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), axis=1)